### ISSUE TITLE
4つのコースの説明を追加

### ISSUE THREAD

**Issue by TakahiroTsunenari** [TakahiroTsunenari/iniad-fake-homepage#6]
4つのコースのページに説明を追加する
・説明文は本当のINIADのWebから適当に拝借

![キャプチャ](https://github.com/TakahiroTsunenari/iniad-fake-homepage/assets/156250623/30aaec6f-4e73-4c73-8a24-7c2dbd2775fd)

**Comment by ikeyamakoto** [comment]
4つのコースの説明文を追記しました。
